Portfolio: finish mobile version
MozamelJawad/My_Portfolio pull request #2
Opened 2023-06-02 17:28 UTC by MozamelJawad

Understand how to parse a Figma design to create a UI.
Use Flexbox to place elements in the page.

2023-06-02 18:12 UTC, Trast00 requested changes
# Change Required ♻️ 
Hi @MozamelJawad , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![almost-there-reach](https://user-images.githubusercontent.com/74411135/225062441-793da0f4-3ef1-4d98-bee9-9c200c7121a7.gif)

## Highlights
- Project look awesome 🍏 🌷 
- Code is clean and well organized 🧼 💯 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@Trast00) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 18:12 UTC, Trast00 commented on index.html
> +      </div>
- [ ] Please ensure the work card matches the provided design with font size (of the title of language tags), colors, and layout size. Also, consider removing the attribute `heigh: 100vh` as it makes the card's height depend on the device which means that your element will not be displayed correctly on all devices. More information in the capture below:
**Figma project**
![image](https://github.com/MozamelJawad/My_Portfolio/assets/74411135/32ace418-7dc5-4df2-8629-786df36fb9c8)

**Your project card design**
 
![image](https://github.com/MozamelJawad/My_Portfolio/assets/74411135/67f47639-8286-4b32-a8df-34e9ea36216d)

This will make your project prettier and make the user know you're an awesome developer as you can precisely follow a professional web developer's design 😃 💪

2023-06-02 18:12 UTC, Trast00 commented on index.html
> +    </p>
- Please make sure your About section matches the figma design. It should be white with a border radius as on the figma design.

**Figma design**
![image](https://github.com/MozamelJawad/My_Portfolio/assets/74411135/110a5826-7ec4-4885-a373-ef1ac3c2aa81)

**Your project design**
![image](https://github.com/MozamelJawad/My_Portfolio/assets/74411135/a4f6861b-3e9d-4870-a5d6-1c42131f7dcb)

This will make your project way prettier which will improve the user experience 📱  😄 👍

2023-06-02 18:12 UTC, Trast00 commented on index.html
> +        </div>
- [ ] Kindly, make sure Skill (`.skills-container`) and Framework (`.frameworks-container`) are in their own `li`. This will improve greatly the semantic of your webpage 😄 which will make your website much more accessible (for users, screen readers, and search engines).

2023-06-03 10:37 UTC, shella12 approved these changes
Hi @MozamelJawad, 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights

- Great design implementation ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 10:37 UTC, shella12 commented on index.html
> +            <img class="image-fluid" src="assets/works/snap.png" alt="">
- [ ] [OPTIONAL] According to the project requirements all of your project cards should have been inclosed in work section and work section should have been aligned using `display:grid`. Currently only one card is enclosed in work section and the rest of the cards are in separate sections each. I would highly recommend you to include all your project cards `.work_cards` into your `work_section` because as mentioned by the previous reviewer "grid is an incredible 💪 😮 tool for responsiveness 😄"

2023-06-03 10:40 UTC, merged